const languageConstant2 = [
  {
    name: "matl",
    label: "matl",
    version: "22.5.0",
    aliases: [],
  },
  {
    name: "matl",
    label: "matl",
    version: "22.7.4",
    aliases: [],
  },
  {
    name: "bash",
    label: "bash",
    version: "5.2.0",
    aliases: ["sh"],
  },
  {
    name: "befunge93",
    label: "befunge93",
    version: "0.2.0",
    aliases: ["b93"],
  },
  {
    name: "bqn",
    label: "bqn",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "brachylog",
    label: "brachylog",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "brainfuck",
    label: "brainfuck",
    version: "2.7.3",
    aliases: ["bf"],
  },
  {
    name: "cjam",
    label: "cjam",
    version: "0.6.5",
    aliases: [],
  },
  {
    name: "clojure",
    label: "clojure",
    version: "1.10.3",
    aliases: ["clojure", "clj"],
  },
  {
    name: "cobol",
    label: "cobol",
    version: "3.1.2",
    aliases: ["cob"],
  },
  {
    name: "coffeescript",
    label: "coffeescript",
    version: "2.5.1",
    aliases: ["coffeescript", "coffee"],
  },
  {
    name: "cow",
    label: "cow",
    version: "1.0.0",
    aliases: ["cow"],
  },
  {
    name: "crystal",
    label: "crystal",
    version: "0.36.1",
    aliases: ["crystal", "cr"],
  },
  {
    name: "dart",
    label: "dart",
    version: "2.19.6",
    aliases: [],
  },
  {
    name: "dash",
    label: "dash",
    version: "0.5.11",
    aliases: ["dash"],
  },
  {
    name: "typescript",
    label: "typescript",
    version: "1.32.3",
    aliases: ["deno", "deno-ts"],
    runtime: "deno",
  },
  {
    name: "javascript",
    label: "javascript",
    version: "1.32.3",
    aliases: ["deno-js"],
    runtime: "deno",
  },
  {
    name: "basic.net",
    label: "basic.net",
    version: "5.0.201",
    aliases: [
      "basic",
      "visual-basic",
      "visual-basic.net",
      "vb",
      "vb.net",
      "vb-dotnet",
      "dotnet-vb",
      "basic-dotnet",
      "dotnet-basic",
    ],
    runtime: "dotnet",
  },
  {
    name: "fsharp.net",
    label: "fsharp.net",
    version: "5.0.201",
    aliases: [
      "fsharp",
      "fs",
      "f#",
      "fs.net",
      "f#.net",
      "fsharp-dotnet",
      "fs-dotnet",
      "f#-dotnet",
      "dotnet-fsharp",
      "dotnet-fs",
      "dotnet-fs",
    ],
    runtime: "dotnet",
  },
  {
    name: "csharp.net",
    label: "csharp.net",
    version: "5.0.201",
    aliases: [
      "csharp",
      "c#",
      "cs",
      "c#.net",
      "cs.net",
      "c#-dotnet",
      "cs-dotnet",
      "csharp-dotnet",
      "dotnet-c#",
      "dotnet-cs",
      "dotnet-csharp",
    ],
    runtime: "dotnet",
  },
  {
    name: "fsi",
    label: "fsi",
    version: "5.0.201",
    aliases: [
      "fsx",
      "fsharp-interactive",
      "f#-interactive",
      "dotnet-fsi",
      "fsi-dotnet",
      "fsi.net",
    ],
    runtime: "dotnet",
  },
  {
    name: "dragon",
    label: "dragon",
    version: "1.9.8",
    aliases: [],
  },
  {
    name: "elixir",
    label: "elixir",
    version: "1.11.3",
    aliases: ["elixir", "exs"],
  },
  {
    name: "emacs",
    label: "emacs",
    version: "27.1.0",
    aliases: ["emacs", "el", "elisp"],
  },
  {
    name: "emojicode",
    label: "emojicode",
    version: "1.0.2",
    aliases: ["emojic"],
  },
  {
    name: "erlang",
    label: "erlang",
    version: "23.0.0",
    aliases: ["erlang", "erl", "escript"],
  },
  {
    name: "file",
    label: "file",
    version: "0.0.1",
    aliases: ["executable", "elf", "binary"],
  },
  {
    name: "forte",
    label: "forte",
    version: "1.0.0",
    aliases: ["forter"],
  },
  {
    name: "forth",
    label: "forth",
    version: "0.7.3",
    aliases: ["gforth"],
  },
  {
    name: "freebasic",
    label: "freebasic",
    version: "1.9.0",
    aliases: ["bas", "fbc", "basic", "qbasic", "quickbasic"],
  },
  {
    name: "awk",
    label: "awk",
    version: "5.1.0",
    aliases: ["gawk"],
    runtime: "gawk",
  },
  {
    name: "c",
    label: "c",
    version: "10.2.0",
    aliases: ["gcc"],
    runtime: "gcc",
  },
  {
    name: "c++",
    label: "c++",
    version: "10.2.0",
    aliases: ["cpp", "g++"],
    runtime: "gcc",
  },
  {
    name: "d",
    label: "d",
    version: "10.2.0",
    aliases: ["gdc"],
    runtime: "gcc",
  },
  {
    name: "fortran",
    label: "fortran",
    version: "10.2.0",
    aliases: ["fortran", "f90"],
    runtime: "gcc",
  },
  {
    name: "go",
    label: "go",
    version: "1.16.2",
    aliases: ["go", "golang"],
  },
  {
    name: "golfscript",
    label: "golfscript",
    version: "1.0.0",
    aliases: ["golfscript"],
  },
  {
    name: "groovy",
    label: "groovy",
    version: "3.0.7",
    aliases: ["groovy", "gvy"],
  },
  {
    name: "haskell",
    label: "haskell",
    version: "9.0.1",
    aliases: ["haskell", "hs"],
  },
  {
    name: "husk",
    label: "husk",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "iverilog",
    label: "iverilog",
    version: "11.0.0",
    aliases: ["verilog", "vvp"],
  },
  {
    name: "japt",
    label: "japt",
    version: "2.0.0",
    aliases: ["japt"],
  },
  {
    name: "java",
    label: "java",
    version: "15.0.2",
    aliases: [],
  },
  {
    name: "jelly",
    label: "jelly",
    version: "0.1.31",
    aliases: [],
  },
  {
    name: "julia",
    label: "julia",
    version: "1.8.5",
    aliases: ["jl"],
  },
  {
    name: "kotlin",
    label: "kotlin",
    version: "1.8.20",
    aliases: ["kt"],
  },
  {
    name: "lisp",
    label: "lisp",
    version: "2.1.2",
    aliases: ["lisp", "cl", "sbcl", "commonlisp"],
  },
  {
    name: "llvm_ir",
    label: "llvm_ir",
    version: "12.0.1",
    aliases: ["llvm", "llvm-ir", "ll"],
  },
  {
    name: "lolcode",
    label: "lolcode",
    version: "0.11.2",
    aliases: ["lol", "lci"],
  },
  {
    name: "lua",
    label: "lua",
    version: "5.4.4",
    aliases: [],
  },
  {
    name: "csharp",
    label: "csharp",
    version: "6.12.0",
    aliases: ["mono", "mono-csharp", "mono-c#", "mono-cs", "c#", "cs"],
    runtime: "mono",
  },
  {
    name: "basic",
    label: "basic",
    version: "6.12.0",
    aliases: ["vb", "mono-vb", "mono-basic", "visual-basic", "visual basic"],
    runtime: "mono",
  },
  {
    name: "nasm",
    label: "nasm",
    version: "2.15.5",
    aliases: ["asm", "nasm32"],
    runtime: "nasm",
  },
  {
    name: "nasm64",
    label: "nasm64",
    version: "2.15.5",
    aliases: ["asm64"],
    runtime: "nasm",
  },
  {
    name: "nim",
    label: "nim",
    version: "1.6.2",
    aliases: [],
  },
  {
    name: "javascript",
    label: "javascript",
    version: "18.15.0",
    aliases: ["node-javascript", "node-js", "javascript", "js"],
    runtime: "node",
  },
  {
    name: "ocaml",
    label: "ocaml",
    version: "4.12.0",
    aliases: ["ocaml", "ml"],
  },
  {
    name: "octave",
    label: "octave",
    version: "8.1.0",
    aliases: ["matlab", "m"],
  },
  {
    name: "osabie",
    label: "osabie",
    version: "1.0.1",
    aliases: ["osabie", "05AB1E", "usable"],
  },
  {
    name: "paradoc",
    label: "paradoc",
    version: "0.6.0",
    aliases: ["paradoc"],
  },
  {
    name: "pascal",
    label: "pascal",
    version: "3.2.2",
    aliases: ["freepascal", "pp", "pas"],
  },
  {
    name: "perl",
    label: "perl",
    version: "5.36.0",
    aliases: ["pl"],
  },
  {
    name: "php",
    label: "php",
    version: "8.2.3",
    aliases: [],
  },
  {
    name: "ponylang",
    label: "ponylang",
    version: "0.39.0",
    aliases: ["pony", "ponyc"],
  },
  {
    name: "prolog",
    label: "prolog",
    version: "8.2.4",
    aliases: ["prolog", "plg"],
  },
  {
    name: "pure",
    label: "pure",
    version: "0.68.0",
    aliases: [],
  },
  {
    name: "powershell",
    label: "powershell",
    version: "7.1.4",
    aliases: ["ps", "pwsh", "ps1"],
    runtime: "pwsh",
  },
  {
    name: "pyth",
    label: "pyth",
    version: "1.0.0",
    aliases: ["pyth"],
  },
  {
    name: "python2",
    label: "python2",
    version: "2.7.18",
    aliases: ["py2", "python2"],
  },
  {
    name: "python",
    label: "python",
    version: "3.10.0",
    aliases: ["py", "py3", "python3", "python3.10"],
  },
  {
    name: "racket",
    label: "racket",
    version: "8.3.0",
    aliases: ["rkt"],
  },
  {
    name: "raku",
    label: "raku",
    version: "6.100.0",
    aliases: ["raku", "rakudo", "perl6", "p6", "pl6"],
  },
  {
    name: "retina",
    label: "retina",
    version: "1.2.0",
    aliases: ["ret"],
  },
  {
    name: "rockstar",
    label: "rockstar",
    version: "1.0.0",
    aliases: ["rock", "rocky"],
  },
  {
    name: "rscript",
    label: "rscript",
    version: "4.1.1",
    aliases: ["r"],
  },
  {
    name: "ruby",
    label: "ruby",
    version: "3.0.1",
    aliases: ["ruby3", "rb"],
  },
  {
    name: "rust",
    label: "rust",
    version: "1.68.2",
    aliases: ["rs"],
  },
  {
    name: "samarium",
    label: "samarium",
    version: "0.3.1",
    aliases: ["sm"],
  },
  {
    name: "scala",
    label: "scala",
    version: "3.2.2",
    aliases: ["sc"],
  },
  {
    name: "smalltalk",
    label: "smalltalk",
    version: "3.2.3",
    aliases: ["st"],
  },
  {
    name: "sqlite3",
    label: "sqlite3",
    version: "3.36.0",
    aliases: ["sqlite", "sql"],
  },
  {
    name: "swift",
    label: "swift",
    version: "5.3.3",
    aliases: ["swift"],
  },
  {
    name: "typescript",
    label: "typescript",
    version: "5.0.3",
    aliases: ["ts", "node-ts", "tsc", "typescript5", "ts5"],
  },
  {
    name: "vlang",
    label: "vlang",
    version: "0.3.3",
    aliases: ["v"],
  },
  {
    name: "vyxal",
    label: "vyxal",
    version: "2.4.1",
    aliases: [],
  },
  {
    name: "yeethon",
    label: "yeethon",
    version: "3.10.0",
    aliases: ["yeethon3"],
  },
  {
    name: "zig",
    label: "zig",
    version: "0.10.1",
    aliases: [],
  },
];

// Function to add version to label
function addVersionToLabel(languages) {
  return languages.map((language) => {
    // Check if label already contains version
    if (!language.label.includes(language.version)) {
      // Append version to label
      language.label += ` (${language.version})`;
    }
    return language;
  });
}

// Add version to label
const updatedLanguageConstant = addVersionToLabel(languageConstant2);

// Print updated languageConstant
console.log(updatedLanguageConstant.length);
