const languageConstant = [
  {
    name: "matl",
    label: "matl (22.5.0)",
    version: "22.5.0",
    aliases: [],
  },
  {
    name: "matl",
    label: "matl (22.7.4)",
    version: "22.7.4",
    aliases: [],
  },
  {
    name: "bash",
    label: "bash (5.2.0)",
    version: "5.2.0",
    aliases: ["sh"],
  },
  {
    name: "befunge93",
    label: "befunge93 (0.2.0)",
    version: "0.2.0",
    aliases: ["b93"],
  },
  { name: "bqn", label: "bqn (1.0.0)", version: "1.0.0", aliases: [] },
  {
    name: "brachylog",
    label: "brachylog (1.0.0)",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "cjam",
    label: "cjam (0.6.5)",
    version: "0.6.5",
    aliases: [],
  },
  {
    name: "clojure",
    label: "clojure (1.10.3)",
    version: "1.10.3",
    aliases: ["clojure", "clj"],
  },
  {
    name: "cobol",
    label: "cobol (3.1.2)",
    version: "3.1.2",
    aliases: ["cob"],
  },
  {
    name: "coffeescript",
    label: "coffeescript (2.5.1)",
    version: "2.5.1",
    aliases: ["coffeescript", "coffee"],
  },
  {
    name: "cow",
    label: "cow (1.0.0)",
    version: "1.0.0",
    aliases: ["cow"],
  },
  {
    name: "crystal",
    label: "crystal (0.36.1)",
    version: "0.36.1",
    aliases: ["crystal", "cr"],
  },
  {
    name: "dart",
    label: "dart (2.19.6)",
    version: "2.19.6",
    aliases: [],
  },
  {
    name: "dash",
    label: "dash (0.5.11)",
    version: "0.5.11",
    aliases: ["dash"],
  },
  {
    name: "typescript",
    label: "typescript (1.32.3)",
    version: "1.32.3",
    aliases: ["deno", "deno-ts"],
    runtime: "deno",
  },
  {
    name: "javascript",
    label: "javascript (1.32.3)",
    version: "1.32.3",
    aliases: ["deno-js"],
    runtime: "deno",
  },
  {
    name: "basic.net",
    label: "basic.net (5.0.201)",
    version: "5.0.201",
    aliases: [
      "basic",
      "visual-basic",
      "visual-basic.net",
      "vb",
      "vb.net",
      "vb-dotnet",
      "dotnet-vb",
      "basic-dotnet",
      "dotnet-basic",
    ],
    runtime: "dotnet",
  },
  {
    name: "fsharp.net",
    label: "fsharp.net (5.0.201)",
    version: "5.0.201",
    aliases: [
      "fsharp",
      "fs",
      "f#",
      "fs.net",
      "f#.net",
      "fsharp-dotnet",
      "fs-dotnet",
      "f#-dotnet",
      "dotnet-fsharp",
      "dotnet-fs",
      "dotnet-fs",
    ],
    runtime: "dotnet",
  },
  {
    name: "csharp.net",
    label: "csharp.net (5.0.201)",
    version: "5.0.201",
    aliases: [
      "csharp",
      "c#",
      "cs",
      "c#.net",
      "cs.net",
      "c#-dotnet",
      "cs-dotnet",
      "csharp-dotnet",
      "dotnet-c#",
      "dotnet-cs",
      "dotnet-csharp",
    ],
    runtime: "dotnet",
  },
  {
    name: "fsi",
    label: "fsi (5.0.201)",
    version: "5.0.201",
    aliases: [
      "fsx",
      "fsharp-interactive",
      "f#-interactive",
      "dotnet-fsi",
      "fsi-dotnet",
      "fsi.net",
    ],
    runtime: "dotnet",
  },
  {
    name: "dragon",
    label: "dragon (1.9.8)",
    version: "1.9.8",
    aliases: [],
  },
  {
    name: "elixir",
    label: "elixir (1.11.3)",
    version: "1.11.3",
    aliases: ["elixir", "exs"],
  },
  {
    name: "emacs",
    label: "emacs (27.1.0)",
    version: "27.1.0",
    aliases: ["emacs", "el", "elisp"],
  },
  {
    name: "emojicode",
    label: "emojicode (1.0.2)",
    version: "1.0.2",
    aliases: ["emojic"],
  },
  {
    name: "erlang",
    label: "erlang (23.0.0)",
    version: "23.0.0",
    aliases: ["erlang", "erl", "escript"],
  },
  {
    name: "file",
    label: "file (0.0.1)",
    version: "0.0.1",
    aliases: ["executable", "elf", "binary"],
  },
  {
    name: "forte",
    label: "forte (1.0.0)",
    version: "1.0.0",
    aliases: ["forter"],
  },
  {
    name: "forth",
    label: "forth (0.7.3)",
    version: "0.7.3",
    aliases: ["gforth"],
  },
  {
    name: "freebasic",
    label: "freebasic (1.9.0)",
    version: "1.9.0",
    aliases: ["bas", "fbc", "basic", "qbasic", "quickbasic"],
  },
  {
    name: "awk",
    label: "awk (5.1.0)",
    version: "5.1.0",
    aliases: ["gawk"],
    runtime: "gawk",
  },
  {
    name: "c",
    label: "c (10.2.0)",
    version: "10.2.0",
    aliases: ["gcc"],
    runtime: "gcc",
  },
  {
    name: "cpp",
    label: "c++ (10.2.0)",
    version: "10.2.0",
    aliases: ["cpp", "g++"],
    runtime: "gcc",
  },
  {
    name: "d",
    label: "d (10.2.0)",
    version: "10.2.0",
    aliases: ["gdc"],
    runtime: "gcc",
  },
  {
    name: "fortran",
    label: "fortran (10.2.0)",
    version: "10.2.0",
    aliases: ["fortran", "f90"],
    runtime: "gcc",
  },
  {
    name: "go",
    label: "go (1.16.2)",
    version: "1.16.2",
    aliases: ["go", "golang"],
  },
  {
    name: "golfscript",
    label: "golfscript (1.0.0)",
    version: "1.0.0",
    aliases: ["golfscript"],
  },
  {
    name: "groovy",
    label: "groovy (3.0.7)",
    version: "3.0.7",
    aliases: ["groovy", "gvy"],
  },
  {
    name: "haskell",
    label: "haskell (9.0.1)",
    version: "9.0.1",
    aliases: ["haskell", "hs"],
  },
  {
    name: "husk",
    label: "husk (1.0.0)",
    version: "1.0.0",
    aliases: [],
  },
  {
    name: "iverilog",
    label: "iverilog (11.0.0)",
    version: "11.0.0",
    aliases: ["verilog", "vvp"],
  },
  {
    name: "japt",
    label: "japt (2.0.0)",
    version: "2.0.0",
    aliases: ["japt"],
  },
  {
    name: "java",
    label: "java (15.0.2)",
    version: "15.0.2",
    aliases: [],
  },
  {
    name: "jelly",
    label: "jelly (0.1.31)",
    version: "0.1.31",
    aliases: [],
  },
  {
    name: "julia",
    label: "julia (1.8.5)",
    version: "1.8.5",
    aliases: ["jl"],
  },
  {
    name: "kotlin",
    label: "kotlin (1.8.20)",
    version: "1.8.20",
    aliases: ["kt"],
  },
  {
    name: "lisp",
    label: "lisp (2.1.2)",
    version: "2.1.2",
    aliases: ["lisp", "cl", "sbcl", "commonlisp"],
  },
  {
    name: "llvm_ir",
    label: "llvm_ir (12.0.1)",
    version: "12.0.1",
    aliases: ["llvm", "llvm-ir", "ll"],
  },
  {
    name: "lolcode",
    label: "lolcode (0.11.2)",
    version: "0.11.2",
    aliases: ["lol", "lci"],
  },
  { name: "lua", label: "lua (5.4.4)", version: "5.4.4", aliases: [] },
  {
    name: "csharp",
    label: "csharp (6.12.0)",
    version: "6.12.0",
    aliases: ["mono", "mono-csharp", "mono-c#", "mono-cs", "c#", "cs"],
    runtime: "mono",
  },
  {
    name: "basic",
    label: "basic (6.12.0)",
    version: "6.12.0",
    aliases: ["vb", "mono-vb", "mono-basic", "visual-basic", "visual basic"],
    runtime: "mono",
  },
  {
    name: "nasm",
    label: "nasm (2.15.5)",
    version: "2.15.5",
    aliases: ["asm", "nasm32"],
    runtime: "nasm",
  },
  {
    name: "nasm64",
    label: "nasm64 (2.15.5)",
    version: "2.15.5",
    aliases: ["asm64"],
    runtime: "nasm",
  },
  { name: "nim", label: "nim (1.6.2)", version: "1.6.2", aliases: [] },
  {
    name: "javascript",
    label: "javascript (18.15.0)",
    version: "18.15.0",
    aliases: ["node-javascript", "node-js", "javascript", "js"],
    runtime: "node",
  },
  {
    name: "ocaml",
    label: "ocaml (4.12.0)",
    version: "4.12.0",
    aliases: ["ocaml", "ml"],
  },
  {
    name: "octave",
    label: "octave (8.1.0)",
    version: "8.1.0",
    aliases: ["matlab", "m"],
  },
  {
    name: "osabie",
    label: "osabie (1.0.1)",
    version: "1.0.1",
    aliases: ["osabie", "05AB1E", "usable"],
  },
  {
    name: "paradoc",
    label: "paradoc (0.6.0)",
    version: "0.6.0",
    aliases: ["paradoc"],
  },
  {
    name: "pascal",
    label: "pascal (3.2.2)",
    version: "3.2.2",
    aliases: ["freepascal", "pp", "pas"],
  },
  {
    name: "perl",
    label: "perl (5.36.0)",
    version: "5.36.0",
    aliases: ["pl"],
  },
  { name: "php", label: "php (8.2.3)", version: "8.2.3", aliases: [] },
  {
    name: "ponylang",
    label: "ponylang (0.39.0)",
    version: "0.39.0",
    aliases: ["pony", "ponyc"],
  },
  {
    name: "prolog",
    label: "prolog (8.2.4)",
    version: "8.2.4",
    aliases: ["prolog", "plg"],
  },
  {
    name: "pure",
    label: "pure (0.68.0)",
    version: "0.68.0",
    aliases: [],
  },
  {
    name: "powershell",
    label: "powershell (7.1.4)",
    version: "7.1.4",
    aliases: ["ps", "pwsh", "ps1"],
    runtime: "pwsh",
  },
  {
    name: "pyth",
    label: "pyth (1.0.0)",
    version: "1.0.0",
    aliases: ["pyth"],
  },
  {
    name: "python2",
    label: "python2 (2.7.18)",
    version: "2.7.18",
    aliases: ["py2", "python2"],
  },
  {
    name: "python",
    label: "python (3.10.0)",
    version: "3.10.0",
    aliases: ["py", "py3", "python3", "python3.10"],
  },
  {
    name: "racket",
    label: "racket (8.3.0)",
    version: "8.3.0",
    aliases: ["rkt"],
  },
  {
    name: "raku",
    label: "raku (6.100.0)",
    version: "6.100.0",
    aliases: ["raku", "rakudo", "perl6", "p6", "pl6"],
  },
  {
    name: "retina",
    label: "retina (1.2.0)",
    version: "1.2.0",
    aliases: ["ret"],
  },
  {
    name: "rockstar",
    label: "rockstar (1.0.0)",
    version: "1.0.0",
    aliases: ["rock", "rocky"],
  },
  {
    name: "rscript",
    label: "rscript (4.1.1)",
    version: "4.1.1",
    aliases: ["r"],
  },
  {
    name: "ruby",
    label: "ruby (3.0.1)",
    version: "3.0.1",
    aliases: ["ruby3", "rb"],
  },
  {
    name: "rust",
    label: "rust (1.68.2)",
    version: "1.68.2",
    aliases: ["rs"],
  },
  {
    name: "samarium",
    label: "samarium (0.3.1)",
    version: "0.3.1",
    aliases: ["sm"],
  },
  {
    name: "scala",
    label: "scala (3.2.2)",
    version: "3.2.2",
    aliases: ["sc"],
  },
  {
    name: "smalltalk",
    label: "smalltalk (3.2.3)",
    version: "3.2.3",
    aliases: ["st"],
  },
  {
    name: "sqlite3",
    label: "sqlite3 (3.36.0)",
    version: "3.36.0",
    aliases: ["sqlite", "sql"],
  },
  {
    name: "swift",
    label: "swift (5.3.3)",
    version: "5.3.3",
    aliases: ["swift"],
  },
  {
    name: "typescript",
    label: "typescript (5.0.3)",
    version: "5.0.3",
    aliases: ["ts", "node-ts", "tsc", "typescript5", "ts5"],
  },
  {
    name: "vlang",
    label: "vlang (0.3.3)",
    version: "0.3.3",
    aliases: ["v"],
  },
  {
    name: "vyxal",
    label: "vyxal (2.4.1)",
    version: "2.4.1",
    aliases: [],
  },
  {
    name: "yeethon",
    label: "yeethon (3.10.0)",
    version: "3.10.0",
    aliases: ["yeethon3"],
  },
  {
    name: "zig",
    label: "zig (0.10.1)",
    version: "0.10.1",
    aliases: [],
  },
];

export default languageConstant;
